---
title: "Analysis"
author: "Xuerui Huang"
date: "5/9/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Load requried package
```{r, results='hide', message=FALSE, warning=FALSE}
library(DESeq2)
library(stringr)
library(ggplot2)
library(ggpubr)
library(dplyr)
library(tidyverse)
library(reshape2)
library(grid)
library(RColorBrewer)
source("~/dataOS/CS_RNA/Annotation.R")
source("~/dataOS/CS_RNA/Functions.R")
```

# Load data and format
```{r}
# laod FPKM data
PBMC_FPKM <- read.csv("~/dataOS/CS_RNA/surface_lipid/PBMC/20190502_FPKMs.txt",sep = "\t")
colnames(PBMC_FPKM)[8:11] <- gsub("*_FPKM","",colnames(PBMC_FPKM)[8:11])
#load gene Count data
PBMC_count <- read.csv("~/dataOS/CS_RNA/surface_lipid/PBMC/htseqCountTotal.txt",sep = "\t")
```

#Plot PCA
```{r}
dds_tot <- DESeqDataSetFromMatrix(countData = as.matrix(PBMC_count_df),
                                  colData = data.frame(row.names =colnames(as.matrix(PBMC_count_df)),            
                                                       condition=c("Sample","Sample","Neg_ctrl","Neg_ctrl")),
                                  design=~condition)

# Plot PCA
require("ggrepel")
z <- plotPCA(rlog(dds_tot))+geom_label_repel(aes(label = name))+
  theme(text = element_text(size = 18,face="bold"),
        axis.text.x = element_text(size = 18,face="bold"),
        axis.text.y = element_text(size = 18,face="bold"),
        plot.title = element_text(size=15,face="bold"))+
  ggtitle("PCA of all the Surface_seq Samples")

z
```


# Count FPKM and plot
```{r}
PBMC_FPKM_count <- get_FPKMcount_table(PBMC_FPKM,8,11,colnames(PBMC_FPKM)[8:11])
plotPCA(PBMC_FPKM_count)

colourCount = length(unique(PBMC_FPKM_count$RNA_type))
getPalette = colorRampPalette(brewer.pal(12, "Set3"))

P <- ggplot(PBMC_FPKM_count, aes(x=variable, y= value, fill = RNA_type)) +
  geom_bar(stat = "identity") + coord_flip()+facet_grid(Condition ~.) +theme() +
  scale_fill_discrete(name = "Assigned_status") + ylab("Count")+ xlab("Sample_ID")+
  #scale_fill_brewer(palette="Set3")+
  ggtitle("FeatureCount_Assign_Distribution")+
  theme(text = element_text(size = 18,face="bold"),
        axis.text.x = element_text(size = 18,face="bold",angle=-40, hjust=.1),
        axis.text.y = element_text(size = 18,face="bold"),
        plot.title = element_text(size=15,face="bold"))+
  scale_fill_manual(values = getPalette(colourCount))
P
ggsave("FPKM_PBMC.png",P,height= 6 , width = 10)
```

# DEseq
```{r}
#Refrom dataframe
PBMC_count_df <- column_to_rownames(PBMC_count,"gene_id")
fil_count_df <- PBMC_count_df[rowSums(PBMC_count_df == 0)<=2,]
PBMC_DEres_df <- perform_DEseq(fil_count_df,2,2)


library(pcaExplorer)

#PBMC_DEres_df <- perform_DEseq(PBMC_count_df,2,2)

test <- subset(PBMC_DEres_df,(padj<0.05)) %>% as.data.frame(.)
test_df <- merge (test,anno_info_Hs, by.x = "Gene_name", by.y = "ENSEMBL")

write.table(test_df,"test_out",row.names = FALSE)
#test2 <- subset(PBMC_DEres_df,(padj<0.05)) %>% as.data.frame(.)

PBMC_cand <- get_DEgenes_info(PBMC_DEres_df,2,0.05,anno_info_Hs,"cands_PBMC_05092019.csv")
hist(PBMC_DEres_df$padj)
```

